version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - HEADLESS=true
      - PORT=3001
    volumes:
      - app_data:/app/data
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2g

volumes:
  app_data: