version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - HEADLESS=true
    volumes:
      - app_data:/app/data
    expose:
      - "3001"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: 2gb
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4g
        reservations:
          cpus: '2.0'
          memory: 2g

volumes:
  app_data: