services:
  playwright-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Node environment
      NODE_ENV: ${NODE_ENV:-production}
      
      # Timezone configuration
      TZ: ${TZ:-America/Sao_Paulo}
      
      # Browser configuration
      HEADLESS: ${HEADLESS:-true}
      
      # Optional: Custom Chrome path (if Chrome is installed in container)
      # CHROME_EXECUTABLE_PATH: /usr/bin/google-chrome
    
    volumes:
      # Persistent data storage
      - playwright_data:/app/data

      # Optional: Mount screenshots separately for easier access
      - ./data/screenshots:/app/data/screenshots

    # Port 3001 is exposed in Dockerfile
    # Platform will handle port mapping automatically
    expose:
      - "3001"
    
    # Required capabilities for browser automation
    cap_add:
      - SYS_ADMIN
    
    # Security options for Chrome/Chromium
    security_opt:
      - seccomp:unconfined
    
    # Shared memory size (required for Chrome/Chromium)
    shm_size: 2gb
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (optional, adjust based on your server)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Named volumes for persistent data
volumes:
  playwright_data:
    driver: local

